app/routes/api.py
from flask import Blueprint, request, jsonify, session
from app.models import User, Post, Comment, Vote
from app.db import get_db
import sys # Access interpreter functions
from app.utils.auth import login_required

bp = Blueprint('api', __name__, url_prefix='/api')

@bp.route('/users', methods=['POST'])
def signup():
  data = request.get_json() # Grabs request info
  db = get_db()
  try: 
    newUser = User( # Creates new user based on request information.
      username = data['username'], # reference items in an object by using object['key']
      email = data['email'],
      password = data['password']
    )
    db.add(newUser) # Stage the new user to commit.
    db.commit()
  
  except: 
    print(sys.exc_info()[0]) # System execution error info
    db.rollback() # Rollback and send error if insert fails
    return jsonify(message='Signup failed, try again.'),500 # Input message, then error code

  session.clear()
  session['user_id'] = newUser.id # Set session user id
  session['loggedIn'] = True # Save session loggedIn object as True

  return jsonify(id = newUser.id)

@bp.route('/users/logout', methods=['POST'])
def logout():
  session.clear() # Clear logged in session
  return '', 204 # Return success, no content

@bp.route('/users/login', methods=['POST'])
def login():
  data = request.get_json()
  db = get_db()
  try: 
    user = db.query(User).filter(User.email == data['email']).one()
  except:
    print(sys.exc_info()[0])
    return jsonify(message = "Login failed. Please try again."),400
  if user.verify_password(data['password']) == False:
    return jsonify(message = "Login failed. Please try again."),400
  
  session.clear()
  session['user_id'] = user.id
  session['loggedIn'] = True

  return jsonify(id = user.id)

@bp.route('/comments', methods=['POST'])
@login_required
def comment():
  data = request.get_json()
  db = get_db()
  try: 
    newComment = Comment(
      comment_text = data['comment_text'],
      post_id = data['post_id'],
      user_id = session.get('user_id')
    )
    
    db.add(newComment)
    db.commit()
  
  except:
    print(sys.exc_info()[0])

    db.rollback()
    return jsonify(message = 'Comment could not be submitted, please try again.'), 500

  return jsonify(id = newComment.id)

@bp.route('/posts/upvote', methods=['PUT'])
@login_required
def upvote():
  data = request.get_json()
  db = get_db()
  print(data['post_id'])
  print(session.get('user_id'))
  try: 
    newVote = Vote( # Create a new vote item
      post_id = data['post_id'],
      user_id = session.get('user_id')
    )
    print(newVote)

    db.add(newVote) # Stage
    db.commit() # Commit
  
  except:
    print(sys.exc_info()[0]) # Print error

    db.rollback() # Rollback commit

    return jsonify(message = "Cannot upvote, please try again."), 500

  return '', 204

@bp.route('/posts', methods = ['POST']) # Create post route
@login_required
def create():
  data = request.get_json()
  db = get_db()

  try:
    newPost = Post(
      title = data['title'],
      post_url = data['post_url'],
      user_id = session.get('user_id')
    )

    db.add(newPost)
    db.commit()
  
  except:
    print(sys.exc_info()[0])
    db.rollback()

    return jsonify(message = 'Cannot create post'), 500
  
  return jsonify(id = newPost.id)

@bp.route('/posts/<id>', methods = ['PUT']) # Update post route, <id> passes id as a parameter
@login_required
def update(id):
  data = request.get_json()
  db = get_db()

  try:
    post = db.query(Post).filter(Post.id == id).one() # Find the post given the id by filtering the results
    post.title = data['title']
    db.commit()
  
  except:
    print(sys.exc_info()[0])
    db.rollback()

    return jsonify(message = "Post not found, please try again."), 404
  
  return '', 204

@bp.route('/posts/<id>', methods = ['DELETE']) # Delete post route
@login_required
def delete(id):
  db = get_db()

  try:
    db.delete(db.query(Post).filter(Post.id == id).one())
    db.commit()

  except:
    print(sys.exc_info()[0])
    db.rollback()

    return jsonify(message = 'Post not found.'), 404
  
  return '', 204

app/routes/dashboard.py
from flask import Blueprint, render_template, session
from app.models import Post
from app.db import get_db
from app.utils.auth import login_required

bp = Blueprint('dashboard', __name__, url_prefix = '/dashboard')

@bp.route('/')
@login_required
def dash():
  db = get_db()
  posts = (
    db.query(Post)
    .filter(Post.user_id == session.get('user_id'))
    .order_by(Post.created_at.desc())
    .all()
  )

  return render_template(
    'dashboard.html',
    posts=posts,
    loggedIn=session.get('loggedIn')
    )

@bp.route('/edit/<id>')
@login_required
def edit(id):
  db = get_db()
  post = db.query(Post).filter(Post.id == id).one()

  return render_template(
    'edit-post.html',
    post=post,
    loggedIn=session.get('loggedIn')
  )

app/templates/dashboard.html
{% extends "layout/main.html" %}

{% block body %}
<section>
  <h2>Create New Post</h2>

  <form class="new-post-form">
    <div>
      <label for="post-title">Title</label>
      <input type="text" id="post-title" name="post-title" />
    </div>
    <div>
      <label for="post-url">Link</label>
      <input id="post-url" name="post-url" />
    </div>
    <button type="submit" class="btn">Create</button>
  </form>
</section>

{% if posts|length > 0 %}
<section>
  <h2>Your Posts</h2>
  <ol>
    {% for post in posts %}
    <li>
      {% include "partials/post-info.html" %}
      <a href="/dashboard/edit/{{post.id}}" class="edit-link">Edit post</a>
    </li>
    {% endfor %}
  </ol>
</section>
{% endif %}

<script src="/javascript/add-post.js"></script>
{% endblock %}

app/templates/edit-post.html
{% extends "layout/main.html" %}

{% block body %}
<article>
  <a href="/dashboard"> &larr; Back to dashboard</a>
  <h2>
    Edit Post
  </h2>
  <form class="edit-post-form">
    <div>
      <input name="post-title" type="text" value="{{post.title}}" />
      <span>({{post.post_url|format_url}})</span>
    </div>
    <div>
      {{post.vote_count}} {{post.vote_count|format_plural('point')}} by you on {{post.created_at|format_date}}
      |
      <a href="/post/{{post.id}}">{{post.comments|length}} {{post.comments|length|format_plural('comment')}}</a>
    </div>
    <button type="submit">Save post</button>
    <button type="button" class="delete-post-btn">Delete post</button>
  </form>
</article>

<form class="comment-form">
  <div>
    <textarea name="comment-body"></textarea>
  </div>

  <div>
    <button type="submit">add comment</button>
  </div>
</form>

{% with comments=post.comments %}
  {% include "partials/comments.html" %}
{% endwith %}

<script src="/javascript/edit-post.js"></script>
<script src="/javascript/delete-post.js"></script>
<script src="/javascript/comment.js"></script>
{% endblock %}

app/templates/homepage.html
{% extends "layout/main.html" %}

{% block body %}
<ol class="post-list">
  {% for post in posts %}
  <li>
    {% include "partials/post-info.html" %}
  </li>
  {% endfor %}
</ol>
{% endblock %}

app/templates/login.html
{% extends "layout/main.html" %}

{% block body %}
<form class="login-form" action="{{url_for('api.login')}}" method="post">
  {# action="{{url_for('applied function')}}" sets the action function. Does not need to specify route #}
  <div>
    <label for="email-login">email:</label>
    <input type="text" id="email-login" />
  </div>
  <div>
    <label for="password-login">password:</label>
    <input type="password" id="password-login" />
  </div>
  <div>
    <button type="submit">login</button>
  </div>
</form>

<form class="signup-form">
  <div>
    <label for="username-signup">username:</label>
    <input type="text" id="username-signup" />
  </div>
  <div>
    <label for="email-signup">email:</label>
    <input type="text" id="email-signup" />
  </div>
  <div>
    <label for="password-signup">password:</label>
    <input type="password" id="password-signup" />
  </div>
  <div>
    <button type="submit">signup</button>
  </div>
</form>

<script src="/javascript/login.js"></script>
{% endblock %}

app/templates/single-post.html
{% extends "layout/main.html" %}

{% block body %}
{% include "partials/post-info.html" %}

{% if loggedIn == True %}
<form class="comment-form">
  <div>
    <textarea name="comment-body"></textarea>
  </div>

  <div>
    <button type="submit">add comment</button>
    <button type="button" class="upvote-btn">upvote</button>
  </div>
</form>
{% endif %}

{% with comments=post.comments %}
  {% include "partials/comments.html" %}
{% endwith %}

{% if loggedIn == True %}
<script src="/javascript/comment.js"></script>
<script src="/javascript/upvote.js"></script>
{% endif %}

{% endblock %}